//
// Created by Theophile Champion on 28/11/2020.
//

#ifndef HOMING_PIGEON_ACTIVE_TRANSITION_NODE_H
#define HOMING_PIGEON_ACTIVE_TRANSITION_NODE_H

#include "FactorNode.h"
#include <torch/torch.h>
#include <api/Aliases.h>
#include <memory>

namespace hopi::nodes {
    class VarNode;
}

namespace hopi::nodes {

    /**
     * Class representing a factor node corresponding to an ActiveTransition distribution.
     */
    class ActiveTransitionNode : public FactorNode {
    public:
        //
        // Factories
        //

        /**
         * Create an ActiveTransition factor node, i.e., representing the distribution P(to|from,action,B).
         * @param from the hidden variable on which the transition is conditioned upon, typically a hidden state
         * @param action the hidden variable representing an action
         * @param to the generated random variable
         * @param B the distribution's parameters, i.e., a 3d random tensor distributed according to a Dirichlet
         * @return the created factor node
         */
        static std::unique_ptr<ActiveTransitionNode> create(RV *from, RV *action, RV *to, RV *B);

        /**
         * Create an ActiveTransition factor node, i.e., representing the distribution P(to|from,action).
         * @param from the hidden variable on which the transition is conditioned upon, typically a hidden state
         * @param action the hidden variable representing an action
         * @param to the generated random variable
         * @return the created factor node
         */
        static std::unique_ptr<ActiveTransitionNode> create(RV *from, RV *action, RV *to);

    public:
        //
        // Constructors
        //

        /**
         * Construct an ActiveTransition factor node, i.e., representing the distribution P(to|from,action,B).
         * @param from the hidden variable on which the transition is conditioned upon, typically a hidden state
         * @param action the hidden variable representing an action
         * @param to the generated random variable
         * @param B the distribution's parameters, i.e., a 3d random tensor distributed according to a Dirichlet
         */
        ActiveTransitionNode(VarNode *from, VarNode *action, VarNode *to, VarNode *B);

        /**
         * Construct an ActiveTransition factor node, i.e., representing the distribution P(to|from,action).
         * @param from the hidden variable on which the transition is conditioned upon, typically a hidden state
         * @param action the hidden variable representing an action
         * @param to the generated random variable
         */
        ActiveTransitionNode(VarNode *from, VarNode *action, VarNode *to);

        //
        // Implement the methods of the FactorNode class
        //

        /**
         * Getter.
         * @param i the index of the parent that must be returned
         * @return the i-the parent of the factor
         */
        VarNode *parent(int i) override;

        /**
         * Getter.
         * @return the child of the factor, i.e., the random variable generated by the factor.
         */
        VarNode *child() const override;

        /**
         * Compute the message towards a specific node
         * @param to the node toward which the message is sent
         * @return the message
         */
        torch::Tensor message(VarNode *to) override;

        /**
         * Compute the Variational Free Energy (VFE) of the factor
         * @return the VFE
         */
        double vfe() override;

    private:
        /**
         * Getter.
         * @return the message towards the generated random variable.
         */
        torch::Tensor toMessage();

        /**
         * Getter.
         * @return the message towards the hidden state upon which the ActiveTransition is conditioned.
         */
        torch::Tensor fromMessage();

        /**
         * Getter.
         * @return the message towards the action upon which the ActiveTransition is conditioned.
         */
        torch::Tensor actionMessage();

        /**
         * Getter.
         * @return the message towards the random variable representing the parameters of the ActiveTransition.
         */
        torch::Tensor bMessage();

        /**
         * Getter.
         * @return if the parameters are distributed according to a Dirichlet, then the expected logarithm of the
         * parameters, otherwise the logarithm of the parameters.
         */
        torch::Tensor getLogB();

    private:
        VarNode *from;
        VarNode *action;
        VarNode *to;
        VarNode *B;
    };

}

#endif //HOMING_PIGEON_ACTIVE_TRANSITION_NODE_H
