//
// Created by tmac3 on 08/12/2020.
//

#ifndef HOMING_PIGEON_2_NODESELECTIONTYPE_H
#define HOMING_PIGEON_2_NODESELECTIONTYPE_H

enum NodeSelectionType : int {
    MIN = 0,
    SAMPLING = 1,
    SOFTMAX_SAMPLING = 2
};

#endif //HOMING_PIGEON_2_NODESELECTIONTYPE_H
